"""Minimal migration runner — applies SQL files from `sql/` in order.

Why not Alembic? Two reasons:
  1. The schema is small + relatively stable; SQL migrations are easier
     to audit than autogenerated diffs.
  2. Court-grade audit means migrations need human-readable SQL we can
     hand to a lawyer if needed.

Tracks applied migrations in the `schema_versions` table. Idempotent —
re-running this is safe; already-applied files are skipped.

CLI:
    python -m mahika.db.migrate          # apply all pending
    python -m mahika.db.migrate --check  # report only, no changes
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from sqlalchemy import text

from mahika.config import settings  # noqa: F401  — ensures .env loaded
from mahika.db.connection import db_engine

SQL_DIR = Path(__file__).resolve().parents[3] / "sql"


def applied_versions() -> set[str]:
    """Read versions already applied. Empty if the table doesn't exist yet."""
    try:
        with db_engine.connect() as conn:
            rows = conn.execute(text("SELECT version FROM schema_versions")).all()
            return {r[0] for r in rows}
    except Exception:
        # schema_versions table itself doesn't exist yet — first migration
        # creates it.
        return set()


def pending_files() -> list[Path]:
    """Return SQL files in `sql/` sorted by name (e.g. `001_*.sql`)."""
    if not SQL_DIR.exists():
        raise FileNotFoundError(f"SQL migration dir missing: {SQL_DIR}")
    return sorted(SQL_DIR.glob("*.sql"))


def version_of(path: Path) -> str:
    """Extract the leading numeric prefix from a migration filename."""
    return path.stem.split("_", 1)[0]


def apply(file: Path) -> None:
    """Run a single SQL file inside a transaction."""
    sql = file.read_text(encoding="utf-8")
    with db_engine.begin() as conn:
        conn.execute(text(sql))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report pending migrations but do not apply.",
    )
    args = parser.parse_args()

    files = pending_files()
    applied = applied_versions()
    pending = [f for f in files if version_of(f) not in applied]

    if not pending:
        print("Mahika DB: schema is up to date.")
        return 0

    print(f"Mahika DB: {len(pending)} migration(s) pending:")
    for f in pending:
        print(f"  - {f.name}")

    if args.check:
        print("Mahika DB: --check supplied, not applying.")
        return 0

    for f in pending:
        print(f"Mahika DB: applying {f.name}...")
        try:
            apply(f)
        except Exception as e:
            print(f"Mahika DB: FAILED on {f.name}: {e}", file=sys.stderr)
            return 1
    print("Mahika DB: all migrations applied.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
