"""Phase 6 cockpit smoke test.

Strategy:
    1. Inject a known token into settings.cockpit_token (in-process — never
       persisted) so we can authenticate without touching Sir's .env.
    2. Boot the FastAPI app via Uvicorn on a random localhost port in a
       background thread.
    3. Hit every endpoint twice:
        a) without the session cookie → expect a redirect to /login
        b) with a valid session cookie → expect 200 + sentinel content
    4. POST /login with the wrong token → expect 401
    5. POST /login with the right token → expect Set-Cookie + redirect
    6. POST /insights/decide → expect redirect + DB write
    7. Tear everything down.

Run:
    python -m tests.test_phase6_smoke
"""
from __future__ import annotations

import socket
import sys
import threading
import time
import uuid
from pathlib import Path

# Allow running directly from `agent/`
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import httpx  # noqa: E402
import uvicorn  # noqa: E402
from sqlalchemy import text  # noqa: E402

from mahika.config import settings  # noqa: E402
from mahika.db.connection import get_session  # noqa: E402

# Inject a test token BEFORE the app module reads settings.
TEST_TOKEN = "PHASE6_SMOKE_" + uuid.uuid4().hex
object.__setattr__(settings, "cockpit_token", TEST_TOKEN)

from mahika.cockpit.app import app  # noqa: E402  — must come after token injection

# ─── Helpers ─────────────────────────────────────────────────────────────


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _wait_ready(url: str, timeout: float = 10.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            r = httpx.get(url, timeout=1.0)
            if r.status_code < 500:
                return True
        except Exception:
            pass
        time.sleep(0.2)
    return False


def _seed_pending_suggestion() -> str:
    """Insert a pending suggestion so the /insights/decide test has something to act on.

    Returns the suggestion UUID for assertion.
    """
    sid = str(uuid.uuid4())
    with get_session() as s:
        s.execute(
            text(
                """
                INSERT INTO suggestions (id, title, body, rationale, status)
                VALUES (CAST(:id AS uuid), :title, :body, :rationale, 'pending')
                """
            ),
            {
                "id": sid,
                "title": "Phase 6 smoke-test suggestion",
                "body": "Pretend Mahika proposed something interesting.",
                "rationale": "Generated by tests/test_phase6_smoke.py",
            },
        )
    return sid


def _cleanup_suggestion(sid: str) -> None:
    with get_session() as s:
        s.execute(text("DELETE FROM suggestions WHERE id = CAST(:id AS uuid)"), {"id": sid})
        s.execute(text("DELETE FROM audit_log WHERE actor = 'sir.cockpit' AND reason LIKE :r"),
                  {"r": f"suggestion {sid[:8]}%"})


# ─── Smoke runner ────────────────────────────────────────────────────────


def main() -> int:
    print("=== Phase 6 cockpit smoke test ===")
    port = _free_port()
    base = f"http://127.0.0.1:{port}"
    print(f"Picked port: {port}")
    print(f"Test token:  {TEST_TOKEN[:24]}…")
    print()

    sid = _seed_pending_suggestion()
    print(f"[setup] Seeded pending suggestion {sid[:8]}…")

    config = uvicorn.Config(app, host="127.0.0.1", port=port, log_level="warning", access_log=False)
    server = uvicorn.Server(config)
    t = threading.Thread(target=server.run, daemon=True)
    t.start()

    try:
        if not _wait_ready(f"{base}/healthz"):
            print("FAIL: server never came up")
            return 1
        print(f"[server] ready at {base}")
        print()

        findings: list[tuple[str, bool]] = []

        # ── healthz (no auth) ─────────────────────────────────────────
        r = httpx.get(f"{base}/healthz")
        findings.append(("GET /healthz → 200 with status payload",
                         r.status_code == 200 and r.json().get("status") == "ok"))

        # ── unauthenticated requests → redirect to /login ─────────────
        client = httpx.Client(follow_redirects=False)
        for path in ("/", "/orders", "/claims", "/audit", "/insights"):
            r = client.get(f"{base}{path}")
            ok = r.status_code in (302, 303) and "/login" in (r.headers.get("location") or "")
            findings.append((f"GET {path} unauth → redirect /login", ok))

        # ── login page renders ────────────────────────────────────────
        r = client.get(f"{base}/login")
        findings.append((
            "GET /login → 200 with login form",
            r.status_code == 200 and "MAHIKA_COCKPIT_TOKEN" in r.text,
        ))

        # ── wrong token → 401 ─────────────────────────────────────────
        r = client.post(f"{base}/login", data={"token": "WRONG"})
        findings.append((
            "POST /login wrong token → 401",
            r.status_code == 401 and "mismatch" in r.text.lower(),
        ))

        # ── right token → 303 with Set-Cookie ─────────────────────────
        r = client.post(f"{base}/login", data={"token": TEST_TOKEN})
        cookie = r.cookies.get("mahika_session")
        findings.append((
            "POST /login right token → 303 + session cookie",
            r.status_code == 303 and bool(cookie),
        ))

        # ── authed requests → 200 with sentinels ──────────────────────
        client.cookies.set("mahika_session", cookie)
        for path, sentinel in (
            ("/", "Status snapshot"),
            ("/orders", "Orders"),
            ("/claims", "Claim queue"),
            ("/audit", "Audit log"),
            ("/insights", "Insights"),
        ):
            r = client.get(f"{base}{path}")
            findings.append((
                f"GET {path} authed → 200 + sentinel",
                r.status_code == 200 and sentinel in r.text,
            ))

        # ── approve suggestion ────────────────────────────────────────
        r = client.post(f"{base}/insights/decide",
                        data={"suggestion_id": sid, "decision": "approved"})
        with get_session() as s:
            row = s.execute(
                text("SELECT status FROM suggestions WHERE id = CAST(:id AS uuid)"),
                {"id": sid},
            ).first()
        decided_status = row[0] if row else None
        findings.append((
            "POST /insights/decide approved → DB updated",
            r.status_code in (302, 303) and decided_status == "approved",
        ))

        # ── invalid decision → 400 ────────────────────────────────────
        r = client.post(f"{base}/insights/decide",
                        data={"suggestion_id": sid, "decision": "maybe"})
        findings.append(("POST /insights/decide bad decision → 400", r.status_code == 400))

        # ── logout clears cookie ──────────────────────────────────────
        r = client.get(f"{base}/logout")
        findings.append((
            "GET /logout → 303 to /login",
            r.status_code == 303 and "/login" in (r.headers.get("location") or ""),
        ))

        print()
        pass_count = 0
        for label, ok in findings:
            print(f"  {'✓' if ok else '✗'} {label}")
            if ok:
                pass_count += 1
        print()
        print(f"=== {pass_count}/{len(findings)} checks passed ===")
        return 0 if pass_count == len(findings) else 1

    finally:
        _cleanup_suggestion(sid)
        server.should_exit = True
        t.join(timeout=5)
        print("[cleanup] server stopped, suggestion deleted")


if __name__ == "__main__":
    raise SystemExit(main())
